In [1]:
import torch

# Create a 2x3 tensor of random numbers
random_tensor = torch.rand(2, 3)
print("Random Tensor:\n", random_tensor)
print("Shape of Random Tensor:", random_tensor.shape)
print("Data Type of Random Tensor:", random_tensor.dtype)

# Create a tensor from a Python list
list_data = [[1, 2, 3], [4, 5, 6]]
list_tensor = torch.tensor(list_data)
print("\nTensor from List:\n", list_tensor)

# Perform a simple operation: addition
added_tensor = random_tensor + list_tensor
print("\nAdded Tensor (random + list):\n", added_tensor)

# Move a tensor to GPU if available (requires CUDA-enabled GPU)
if torch.cuda.is_available():
    gpu_tensor = random_tensor.to('cuda')
    print("\nTensor on GPU:\n", gpu_tensor)
else:
    print("\nCUDA not available or not configured. Tensor remains on CPU.")

Random Tensor:
 tensor([[0.5299, 0.2455, 0.0925],
        [0.9868, 0.4514, 0.8719]])
Shape of Random Tensor: torch.Size([2, 3])
Data Type of Random Tensor: torch.float32

Tensor from List:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Added Tensor (random + list):
 tensor([[1.5299, 2.2455, 3.0925],
        [4.9868, 5.4514, 6.8719]])

Tensor on GPU:
 tensor([[0.5299, 0.2455, 0.0925],
        [0.9868, 0.4514, 0.8719]], device='cuda:0')


In [2]:
import torch

# Our "ingredients" (tensors) that we want PyTorch to "watch" and figure out how to tweak.
# By setting 'requires_grad=True', we're telling Autograd: "Keep an eye on this one!"
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

# These are the "steps in our recipe" (operations) that lead to our final "cake" (b).
# PyTorch is secretly remembering each of these steps because x and y are being "watched."
z = x * y       # Step 1: Multiply x and y
a = z + 5       # Step 2: Add 5 to the result of z
b = a ** 2      # Step 3: Square the result of a (this is our "final taste" or output)

print("x:", x)
print("y:", y)
print("z = x * y:", z)
print("a = z + 5:", a)
print("b = a ** 2:", b)

# This is the "Go Backwards and Adjust!" command.
# We're telling Autograd: "Okay, now that we have 'b', go back through all the steps you remembered
# and calculate the 'tweak amount' (gradient) for x and y to change 'b'."
b.backward()

# Now we can see the "tweak amounts" (gradients) that Autograd calculated.
# x.grad tells us how much to adjust x to affect b.
# y.grad tells us how much to adjust y to affect b.
print("\n'Tweak amount' for x (gradient of b with respect to x):", x.grad)
print("'Tweak amount' for y (gradient of b with respect to y):", y.grad)

x: tensor(2., requires_grad=True)
y: tensor(3., requires_grad=True)
z = x * y: tensor(6., grad_fn=<MulBackward0>)
a = z + 5: tensor(11., grad_fn=<AddBackward0>)
b = a ** 2: tensor(121., grad_fn=<PowBackward0>)

'Tweak amount' for x (gradient of b with respect to x): tensor(66.)
'Tweak amount' for y (gradient of b with respect to y): tensor(44.)
